### Numpy Primer part 4
----------------------

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
%matplotlib inline
import random

### Matrix operations

In [2]:
x1 = np.random.randn(5,5)
mat = x1.T.dot(x1) # multipliying a matrix by its transpose

In [3]:
from numpy.linalg import inv, qr

inv(mat) # it calculates the inverse of an specific matrix

array([[ 13.81121665,  -1.0026904 , -24.0421017 ,   9.25498594,
         -8.90517223],
       [ -1.0026904 ,   0.12933752,   1.75722356,  -0.58793008,
          0.65466542],
       [-24.0421017 ,   1.75722356,  42.58521313, -16.69431075,
         16.05840195],
       [  9.25498594,  -0.58793008, -16.69431075,   7.99631754,
         -6.24737899],
       [ -8.90517223,   0.65466542,  16.05840195,  -6.24737899,
          6.34854593]])

In [4]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  3.12115264e-16,  1.93044132e-14,
         7.22190861e-15, -6.21515140e-15],
       [ 2.18593723e-15,  1.00000000e+00, -6.44395232e-15,
        -4.75315861e-15,  4.79435590e-15],
       [-2.20546156e-14,  1.38631426e-15,  1.00000000e+00,
         3.69057403e-15,  4.49581750e-15],
       [-2.50356305e-15,  2.05068204e-16,  2.48047245e-15,
         1.00000000e+00, -8.90341771e-16],
       [ 1.38098441e-14, -1.49578942e-15, -1.91666806e-14,
         1.56700746e-15,  1.00000000e+00]])

In [5]:
q,r = qr(mat) # it factorizes the matrix
r

array([[-11.88329961,   5.45507315, -11.30252833,  -2.30065139,
          9.15675482],
       [  0.        , -20.06737531,   1.63742798,   1.44739799,
         -0.64296385],
       [  0.        ,   0.        ,  -1.18996615,  -0.24502606,
          2.89584932],
       [  0.        ,   0.        ,   0.        ,  -0.66400111,
         -0.70153347],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.04897393]])

### List of most common numpy linear algebra functions
[linear algebra](http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html)

### List of most common random generation numbers functions
[Random generation functions](http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.random.html)

### Use of If with Numpy ( Comparable to Excel If )

In [6]:
arr17 = np.random.randn(4,4)
arr17

array([[ 0.69227197, -0.32550837, -0.20500805,  0.13103086],
       [ 1.40494573, -1.23653453,  1.18952148, -0.67596642],
       [ 3.72901668, -1.20565041,  0.77469263, -1.28979373],
       [ 0.23445884,  0.11478044, -0.04877816, -0.67188172]])

In [7]:
np.where(arr17 > 0, 2, -2) # typical if where if condition is met do x if not do y

array([[ 2, -2, -2,  2],
       [ 2, -2,  2, -2],
       [ 2, -2,  2, -2],
       [ 2,  2, -2, -2]])

### Solving Systems of Linear Equations

We are going to solve equations of type:

$$
a \cdot x = b
$$

Consider the system of linear equations which fits the above type:

\begin{eqnarray}
a_1^1 \cdot x_1 + a_1^2 \cdot x_1 = b_1 \\
a_2^1 \cdot x_2 + a_2^2 \cdot x_2 = b_2
\end{eqnarray}

First, matrix $a$.

In [8]:
a = np.array([[3, 1], [1, 2]])

Second, vector $b$.

In [9]:
b = np.array([9, 8])

Third, the solution.

In [10]:
x = np.linalg.solve(a, b)
x

array([2., 3.])

In [11]:
print (np.dot(a, x))  # checking
print ('Results matches vector b')

[9. 8.]
Results matches vector b


### Random Numbers

NumPy has powerful pseudo-random number generating functions available. Most of them get covered later. Very often, we use **standard-normally distributed pseudo-random numbers**.

In [12]:
np.random.standard_normal()  # single number

-0.4197399281063725

In [13]:
np.random.standard_normal(5)  # 1d array

array([-0.40374985,  0.08475804, -0.53360491,  0.34517842,  0.70249989])

In [14]:
a = np.random.standard_normal((2, 6)) * 0.5  # 2d array
a

array([[-0.13257874, -0.43821735,  0.36587122,  0.01703711, -0.59774586,
         0.5314858 ],
       [-0.6614018 , -0.36335699, -0.30808739,  0.36912834,  0.60373163,
        -0.67955325]])

In [15]:
np.round(a, 2)

array([[-0.13, -0.44,  0.37,  0.02, -0.6 ,  0.53],
       [-0.66, -0.36, -0.31,  0.37,  0.6 , -0.68]])